server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: 
      username: admin
      password: 
  thymeleaf:
      cache: false 
  
      
mybatis:
  mapper-locations:
  - /mappers/*.xml
  

     


